name: CI

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install python and pytest
        run: sudo apt-get install python pytest
        
      - name: Run pytest
        run: python -m pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
