name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: apt install python
      - name: Install pytest
        run: apt install python-pytest
      - name: Run pytest
        run: pytest
