name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python and pytest
        run: sudo apt-get install python python-pytest
      - name: Run pytest
        run: pytest
  lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: github/super-linter@v3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
