name: Inline pytest

on:
  workflow_dispatch:

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pip
        run: |
          sudo apt install python3 python3-pip
          pip install pytest
          python -m pytest
