name: "uses" pytest

on:
  workflow_dispatch:

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
